services:
  postgres:
    image: postgres
    environment:
      - POSTGRESS_PASSWORD=postgrespw
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postresql/data
volumes:
  pgdata: